# Generated by Django 6.0.6 on 2026-07-09 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_experience',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_summary',
        ),
        migrations.CreateModel(
            name='ShiftExcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_summary', models.TextField(blank=True, null=True)),
                ('cv_skills', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('cv_experience', models.TextField(blank=True, null=True)),
                ('cv_education', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
