# Generated by Django 6.0.6 on 2026-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_remove_userprofile_cv_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='max_interns',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of students allowed to be hired for this position.'),
        ),
    ]
