# Generated by Django 6.0.6 on 2026-07-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0006_weeklyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='student_portal.application'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='instructor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Needs Revision')], default='Pending', max_length=20),
        ),
    ]
